FROM ubuntu:18.04

ENV CONFLUENT_HOME=/usr \
    TERM=xterm-256color

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git \
        curl \
        wget \
        jq \
        netcat \
        httpie \
        peco \
        vim \
        expect \
    && mkdir ~/confluent-v1 \
    && curl --http1.1 -L https://cnfl.io/cli | sh -s -- -b ~/confluent-v1 v1.43.1 \
    && echo '#!/bin/bash\nHOME=~/confluent-v1 ~/confluent-v1/confluent "$@"' > /usr/bin/confluent-v1 \
    && chmod +x /usr/bin/confluent-v1 \
    && curl --http1.1 -L https://cnfl.io/cli | sh -s -- -b /usr/bin \
    && rm -rf /var/lib/apt/lists/*
